### PR TITLE
CTCP-3880: Rename carrier details eori to eoriTCUIN and make supply chain actor utilise too

### PR DESCRIPTION
**Pull request by Reece-Carruthers**

### CODE REVIEW

**Comment by Reece-Carruthers** [comment]
rebuild

**Comment by Reece-Carruthers** [comment]
[screen-recorder-tue-jun-11-2024-14-00-44.webm](https://github.com/hmrc/ctc-departure-transport-details-frontend/assets/99188015/2d030113-cbdf-44f3-97a0-1f6496f91b36)

**Comment by Reece-Carruthers** [comment]
working after refactor

[screen-recorder-wed-jun-12-2024-08-59-57.webm](https://github.com/hmrc/ctc-departure-transport-details-frontend/assets/99188015/da77b201-339f-4900-b211-242f33c24630)

**Comment by Reece-Carruthers** [comment]
image
image
image

**Review by jackheslop96 — APPROVED** [review]

**Review by vajarova — APPROVED** [review]

**Pull request merged**
